/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Tahsel.UI;

/**
 *
 * @author Bat
 */
public class JPanelParents extends javax.swing.JPanel {

    /**
     * Creates new form JPanelParents
     */
    public JPanelParents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelGrade = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSearchGrade = new javax.swing.JTextField();
        jButtonSearchGrade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGrade = new javax.swing.JTable();
        jPanelKG = new javax.swing.JPanel();
        jSplitPaneKG = new javax.swing.JSplitPane();
        jPanel3KG = new javax.swing.JPanel();
        jTextFieldSearchKG = new javax.swing.JTextField();
        jButtonSearchKG = new javax.swing.JButton();
        jLabelKG = new javax.swing.JLabel();
        jPanelKG2 = new javax.swing.JPanel();
        jScrollPaneKG = new javax.swing.JScrollPane();
        jTableKG = new javax.swing.JTable();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jButtonSearchGrade.setText("»ÕÀ");

        jLabel1.setText("»ÕÀ »—ﬁ„ Ê·Ì «·«„—:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jButtonSearchGrade)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSearchGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchGrade)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jTableGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableGrade);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout jPanelGradeLayout = new javax.swing.GroupLayout(jPanelGrade);
        jPanelGrade.setLayout(jPanelGradeLayout);
        jPanelGradeLayout.setHorizontalGroup(
            jPanelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelGradeLayout.setVerticalGroup(
            jPanelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jTabbedPane.addTab("Grade", jPanelGrade);

        jSplitPaneKG.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jButtonSearchKG.setText("»ÕÀ");

        jLabelKG.setText("»ÕÀ »—ﬁ„ Ê·Ì «·«„—:");

        javax.swing.GroupLayout jPanel3KGLayout = new javax.swing.GroupLayout(jPanel3KG);
        jPanel3KG.setLayout(jPanel3KGLayout);
        jPanel3KGLayout.setHorizontalGroup(
            jPanel3KGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3KGLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jButtonSearchKG)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSearchKG, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKG)
                .addContainerGap())
        );
        jPanel3KGLayout.setVerticalGroup(
            jPanel3KGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3KGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3KGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchKG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchKG)
                    .addComponent(jLabelKG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPaneKG.setTopComponent(jPanel3KG);

        jTableKG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneKG.setViewportView(jTableKG);

        javax.swing.GroupLayout jPanelKG2Layout = new javax.swing.GroupLayout(jPanelKG2);
        jPanelKG2.setLayout(jPanelKG2Layout);
        jPanelKG2Layout.setHorizontalGroup(
            jPanelKG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneKG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanelKG2Layout.setVerticalGroup(
            jPanelKG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneKG, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        jSplitPaneKG.setRightComponent(jPanelKG2);

        javax.swing.GroupLayout jPanelKGLayout = new javax.swing.GroupLayout(jPanelKG);
        jPanelKG.setLayout(jPanelKGLayout);
        jPanelKGLayout.setHorizontalGroup(
            jPanelKGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneKG, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelKGLayout.setVerticalGroup(
            jPanelKGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneKG)
        );

        jTabbedPane.addTab("KG", jPanelKG);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearchGrade;
    private javax.swing.JButton jButtonSearchKG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelKG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3KG;
    private javax.swing.JPanel jPanelGrade;
    private javax.swing.JPanel jPanelKG;
    private javax.swing.JPanel jPanelKG2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneKG;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPaneKG;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableGrade;
    private javax.swing.JTable jTableKG;
    private javax.swing.JTextField jTextFieldSearchGrade;
    private javax.swing.JTextField jTextFieldSearchKG;
    // End of variables declaration//GEN-END:variables
}
