/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tahsel;

import Tahsel.Database.DatabaseBuilder;
import Tahsel.Database.SearchHelper;
import Tahsel.Objects.User;
import Tahsel.UI.AddUser;
import Tahsel.UI.Login;
import Tahsel.UI.TheMainTable;
import com.formdev.flatlaf.FlatDarculaLaf;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFrame;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class App {

    public static void main(String[] args) {

        try {
            UIManager.setLookAndFeel(new FlatLightLaf()); // For dark theme
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }

        DatabaseBuilder.createAllTables();
        User user = readUserFromFile();
        if (user != null) {
            TheMainTable mainTable = new TheMainTable(user);
            mainTable.setVisible(true);
        } else {
            Login login = new Login();
            login.setVisible(true);

        }

    }

    public static User readUserFromFile() {

        // Define the path for the "Sunrise" folder inside Documents
        File sunriseFolder = new File(new File(System.getProperty("user.home"), "Documents"), "Sunrise");
        // Check if the Sunrise folder exists, if not, create it
        if (!sunriseFolder.exists()) {
            boolean created = sunriseFolder.mkdir(); // Create the Sunrise folder
            if (created) {
                System.out.println("Folder 'Sunrise' was created inside Documents.");
            } else {
                System.out.println("Failed to create 'Sunrise' folder.");
                return null;
            }
        }
        // Define the file path for the "hello.txt" file inside "Sunrise"
        File file = new File(sunriseFolder, "RM.txt");
        // Check if the file exists
        if (!file.exists()) {
            System.out.println("File does not exist.");
            return null;
        }
        // Read the file using BufferedReader
        try ( BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line = reader.readLine();
            User dbUser = SearchHelper.getUserByID(line);
            if (dbUser != null) {
                return dbUser;
            } else {
                return null;
            }
        } catch (IOException e) {
            System.out.println("An error occurred while reading the file: " + e.getMessage());
            return null;
        }
    }

}
